### ISSUE TITLE
[BUG] Feature flags string inconsistency in localized strings.xml files

### ISSUE THREAD

**Issue by Mehlsine** [crimera/piko#102]
Hello crimera,
I believe _Feature flags_ string's value in mod menu is fetched from strings.xml in values-v21 folder (_piko_title_feature_flags_) and not from localized strings.xml files (_piko_pref_feature_flags_), and that's what makes it keep its original English value.

I checked mod menu in a few languages that have _piko_pref_feature_flags_ string translated, and this issue persists in all of them:

![ResizedImage_2024-04-15_06-55-34_0](https://i.imgur.com/dtf31Oe.jpeg)
![ResizedImage_2024-04-15_06-55-34_1](https://i.imgur.com/t04vg24.jpeg)

**Comment by crimera** [comment]
Thanks for letting us know. should be fixed on https://github.com/crimera/revanced-integrations/commit/2afce734d7ce7d0d713beda1b9e82d6a11818698
