### ISSUE TITLE
Edit Navigation Bar not working correctly

### ISSUE THREAD

**Issue by LovecraftianGodsKiller** [crimera/piko#108]
So I have the patch to edit the navigation bar options applied but when go to edit them and then click on save, the layout I applied does not get applied.

**Comment by Mehlsine** [comment]
Have you tried force stopping the app then opening it again after editing navbar layout? App restart is required if you want new settings to be applied.

**Comment by LovecraftianGodsKiller** [comment]
I hwve force stopped the app. The same thing happens

**Comment by Quasar-0330** [comment]
In my case the notifications are not hidden and I can't see my bookmarks

**Comment by LovecraftianGodsKiller** [comment]
> In my case the notifications are not hidden and I can't see my bookmarks

Yeah, when I modify it, it just brings me down to 4 options.
Don't remember what 4 but I've just come to accept it at this point and not bother with it leaving at the default layout.

**Comment by Morafoka69** [comment]
> So I have the patch to edit the navigation bar options applied but when go to edit them and then click on save, the layout I applied does not get applied.

What I did is to unselect all the navigation icons, then select them in the order I want them to be, then force stop the app. Maybe you can try this?

**Comment by Quasar-0330** [comment]
![Screenshot_20240503-165214_X](https://github.com/crimera/piko/assets/95518809/cafdfc67-6429-4559-9506-59aee7e1427c)

The navigation bar issue has been fixed, but when I open a bookmark, it shows "Cannot load folder" as shown in this image

**Comment by crimera** [comment]
> ![Screenshot_20240503-165214_X](https://private-user-images.githubusercontent.com/95518809/327688238-cafdfc67-6429-4559-9506-59aee7e1427c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwMDQ3MDAsIm5iZiI6MTcxNTAwNDQwMCwicGF0aCI6Ii85NTUxODgwOS8zMjc2ODgyMzgtY2FmZGZjNjctNjQyOS00NTU5LTk1MDYtNTlhZWU3ZTE0MjdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA2VDE0MDY0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxNjZmMjQwZmVjZmVjYjIxZWRkZTAxZTVmMDk2Y2Y4MDRhZmZlMTQ1M2VkNzlmYmIyNzQ2NDI2M2ExY2Y5Y2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YgHxNNy1HXpKoHUr7rA7wj7bEKrekyM_LzN_WGwlFRo)
> 
> The navigation bar issue has been fixed, but when I open a bookmark, it shows "Cannot load folder" as shown in this image

yep, the bookmark icon opens the bookmarksfolder which is a premium feature

**Comment by TheXug** [comment]
Had this issue with 11.76.0-release.0 patch 3.0.0.
Clearing cache worked.
