### ISSUE TITLE
Change 'search X' to 'search on Twitter

### ISSUE THREAD

**Issue by Kdroidwin** [crimera/piko#117]
Replace X with Twitter
![Screenshot_20240416-182423](https://github.com/crimera/piko/assets/144515909/a85c3abb-fd6d-44e0-8107-0df5fc023b5d)

**Comment by LovecraftianGodsKiller** [comment]
I second this

**Comment by Kdroidwin** [comment]
Please support Japanese.

**Comment by LovecraftianGodsKiller** [comment]
> Please support Japanese.

I'm pretty sure that as long as you use the japanese translation patch, or whatever it is, it should be compatible.
It just wouldn't make sense otherwise
