### ISSUE TITLE
Click feature flag crash

### ISSUE THREAD

**Issue by lgernierO** [crimera/piko#122]
There is no add feature flag to turn on, but adding one will crash.
The functionality implemented by the feature flag works normally if it has been added, but clicking the feature flag in mod setting will crash.
Twitter v10.37.0 with latest patch dev9.
[crash-com-twitter-android-18_04-08-14-52_572.zip](https://github.com/crimera/piko/files/15018342/crash-com-twitter-android-18_04-08-14-52_572.zip)

**Comment by crimera** [comment]
hello, the issue should be fixes with this build. https://github.com/crimera/revanced-integrations/commit/ff144f79ce2e9645f8bd680f12a3329c2f74e3e2

**Comment by lgernierO** [comment]
OK, it's been fixed.
