### ISSUE TITLE
Bug `Download patch` acts weirdly

### ISSUE THREAD

**Issue by What-Zit-Tooya** [crimera/piko#15]
Compared to revanced patches https://github.com/ReVanced/revanced-patches/commit/2c20844eaae698f185a9d321e2c70bde4b485cee and this https://github.com/ReVanced/revanced-patches/commit/d0f91c8550592723e1252e1af2971b508591dd59 , download video feature patch is weirdly. In same post, i can't download the video with crimera patch, but while using revanced patches i can download the video.

I am using the revanced CLI and this command:
```
java -jar revanced-cli-4.4.0-all.jar patch -p -o X_10.30.0-release.0-all-archs-crimera.apk --options options.json -b revanced-patches-1.9.0-dev.1.jar --alias=[snip] --keystore-password=[snip] --keystore-entry-password=[snip] --keystore=[snip].keystore -m revanced-integrations-1.2.0.apk com.twitter.android-10.30.0-release.0-all-archs.apk -i "Hide For You" -i "Google Ads Patch" -i "Hide Banner" -i "Hide Live Threads"
```

Example post link:
`https://twitter.com/le_sserafim/status/1763784207703441728`

Screenshot from crimera X:
![Screenshot_20240302-135743](https://github.com/crimera/piko/assets/9832875/9967fe52-71cd-44b3-803e-ef816f9cc188)

Screenshot from Revanced X:
![Screenshot_SS](https://github.com/crimera/piko/assets/9832875/d8ad7b35-cb41-4343-a829-239636e62a4a)

I dont know if this bug already reported, but thats happened on my device.

**Comment by crimera** [comment]
Revanced patch targets the download sheet from the video player while the piko patch only targets the sheet from when you hold the video on the actual post. Will check back on this later.

A workaround for this is to include the official revanced patch bundle when building.

**Comment by crimera** [comment]
It seems revanced official patch bundle now gets all the videos, will be disabling my own download patch in favor of theirs.
