### ISSUE TITLE
bug: App keeps auto refreshing when opened

### ISSUE THREAD

**Issue by Kuddus73** [crimera/piko#176]
https://github.com/crimera/piko/assets/127908708/7ac43a48-45ab-458a-97fa-4a659e9b1998

**Comment by Morafoka69** [comment]
Thank you for speaking up. I thought I was the only one experiencing this.

**Comment by crimera** [comment]
This may be a bug with the twitter app itself. Tried the official apps and it also happens there

**Comment by Kuddus73** [comment]
> This may be a bug with the twitter app itself.

Because of this bug I went back to v10.28.0, and it doesn't happen there:

https://github.com/crimera/piko/assets/127908708/7b0944ae-fc6c-4d74-a3aa-0713ed9bda29

**Comment by Morafoka69** [comment]
@crimera please is this issue still happening in the latest version?
