### ISSUE TITLE
Bookmarks in a nav bar won't load

### ISSUE THREAD

**Issue by Bec-de-Xorbin** [crimera/piko#185]
If a bookmark icon is put in a nav bar it won't load and gives an error: "Folders aren't loading now. Try again later." Using the latest version from piko-builds releases.

![Screenshot_2024-05-08-12-45-48-933_com twitter android-edit](https://github.com/crimera/piko/assets/1503339/061419cd-598f-4ca2-aa57-d6d23520ca0e)

**Comment by Quasar-0330** [comment]
https://github.com/crimera/piko/issues/108
