### ISSUE TITLE
Enhancement: Switch the home icon in navigation bar back to the previous birdhouse home icon in "Bring back twitter" patch.

### ISSUE THREAD

**Issue by WelsonLiong** [crimera/piko#239]
This is just a cosmetic feature but it would be a great little touch to the patch.

The birdhouse home icon vs the current home icon:
![20240523_225226.jpg](https://github.com/crimera/piko/assets/89066255/94f9d929-8d50-42a1-8143-82a354ae5ef7)

**Comment by crimera** [comment]
https://github.com/crimera/piko/pull/342
