### ISSUE TITLE
Doubled command patch 

### ISSUE THREAD

**Issue by What-Zit-Tooya** [crimera/piko#26]
With standar patch you mention in [notes](https://github.com/crimera/piko?tab=readme-ov-file#notes):

```
java -jar cli.jar patch \
  -b official-revanced.jar \
  -b piko.jar \
  -m integrations.apk \
  -e "Unlock downloads"
  -o out.apk input.apk
```

There are doubled patch which is `Hide Recommended Users` like this:

![image](https://github.com/crimera/piko/assets/9832875/cd16303c-df9d-428a-95cb-c67b1741a657)

You should add exeptions for that, e.g

```
java -jar cli.jar patch \
  -b official-revanced.jar \
  -b piko.jar \
  -m integrations.apk \
  -e "Unlock downloads"
  -e "Hide Recommended Users"
  -o out.apk input.apk
```

Either piko patch or revanced patch you excluded.

**Comment by crimera** [comment]
https://github.com/crimera/piko/commit/0221131204dffa4531eb5bb5b78348b43633df4b
