### ISSUE TITLE
Bug: "Download all" only download two media

### ISSUE THREAD

**Issue by 0frd** [crimera/piko#332]
![Screenshot_2024-08-08-14-43-27-742_com google android apps photos-edit](https://github.com/user-attachments/assets/28604c64-f76e-477d-8d1d-500fbfdb7226)
![Screenshot_2024-08-08-14-40-46-906_com twitter android](https://github.com/user-attachments/assets/8b120ad3-e100-4141-bb47-a72f21f4f66a)

**Comment by Morafoka69** [comment]
I think you used the default dl button of Twitter.

**Comment by crimera** [comment]
Fixed with: https://github.com/crimera/revanced-integrations/commit/91ef652e39b96e005ebeda5f3f72bf19a62db91f
