### ISSUE TITLE
Premium option still showing in the Side Bar. 

### ISSUE THREAD

**Issue by Morafoka69** [crimera/piko#333]
I disabled this in the Piko Settings and it's still showing. Please help.

I'm using the latest patches (V1.34.1).

Thank you in anticipation. 
![Sidebar](https://github.com/user-attachments/assets/28dda369-2299-451c-aaaa-2b5f25096642)
![Screenshot_20240808-120202](https://github.com/user-attachments/assets/e9835a19-631d-441c-8ddf-90e4a3e20d68)

**Comment by mortyobnoxious** [comment]
Hi you can use "feature flags" and search for "subscriptions_dash_item_enabled" to remove it as temp solution.

Like this:

![IMG_20240813_010926_775](https://github.com/user-attachments/assets/0c87b98b-b8a0-420d-8bbe-48becb242650)

**Comment by Morafoka69** [comment]
> Hi you can use "feature flags" and search for "subscriptions_dash_item_enabled" to remove it as temp solution.
> 
> Like this:
> 
> ![IMG_20240813_010926_775](https://private-user-images.githubusercontent.com/42044258/357215683-0c87b98b-b8a0-420d-8bbe-48becb242650.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1MzIxMjcsIm5iZiI6MTcyMzUzMTgyNywicGF0aCI6Ii80MjA0NDI1OC8zNTcyMTU2ODMtMGM4N2I5OGItYjhhMC00MjBkLThiYmUtNDhiZWNiMjQyNjUwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEzVDA2NTAyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2MDkxNzMzZmY5MjRiNDNkYzg5MjI3M2FiY2E5Y2UxN2JkMzhiMTAyN2MyMWEzMmUyYTVjN2ZiNzgzOWFiYzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.un0A0r2uOwJ2Yy0kWL5SYAuGQtIxM3GhKP9EZFAGui0)

Thank you for replying. Please I don't know anything about Feature Flags and I want to use them very much but have no one to educate me. Please could you? How do I get them or use them?

Thank you in anticipation.

**Comment by mortyobnoxious** [comment]
@Morafoka69 

Follow these steps:

pico settings > feature flags > plus sign > search flags > subscriptions_dash_item_enabled

then deactivate it like in the picture above .

**Comment by Morafoka69** [comment]
Thanks a lot for this. I really appreciate.

Please is there something like a repo where the functions of all the Feature Flags are stated? I think I'd like to use them. Thank you.

**Comment by mortyobnoxious** [comment]
Not that I know of. Sorry.

**Comment by Morafoka69** [comment]
> Not that I know of. Sorry.

Thanks for everything. @crimera if you would be so kind, I'll be very grateful.
