### ISSUE TITLE
Setting for Default 'Sort Replies' Option

### ISSUE THREAD

**Issue by mortyobnoxious** [crimera/piko#341]
Can you add a setting to choose a default 'Sort Replies' option?

![image](https://github.com/user-attachments/assets/bcecc82a-a04e-4bec-9d84-3311142f6bc1)

**Comment by crimera** [comment]
https://github.com/crimera/piko/pull/340/commits/121b8a6e9345ea462ad9cb06f7b20f863fc08d4a
