### ISSUE TITLE
(Suggestion) Add patch to revert the X name and icon back to the original

### ISSUE THREAD

**Issue by ashuramaruzxc** [crimera/piko#38]
Currently there's a way of doing this is only by modifying an already modified by the patcher apk yourself, however it's a pretty timeconsuming and automating it via revanced patcher would be much preferable.

#### PS: By revert the X name and icons i mean reverting the UI completely including splash screen topbar icon, the app name and icon itself

**Comment by crimera** [comment]
https://github.com/crimera/piko/commit/b299b0c076a9ef68970bc57547830027d336b442
