### ISSUE TITLE
Feature Request: make "Jobs" button hideable with "Side bar items to hide"

### ISSUE THREAD

**Issue by QWIILXEY** [crimera/piko#398]
Twitter recently added a "Jobs" button to the side bar in the mobile app. could this be hidden along with other side bar items?

proof:
![puOQayzbeqEtyd8hklbjH2HnFN9BI4Iv.png](https://github.com/user-attachments/assets/358a67c3-4d4a-480c-9da8-37df2edbba29)
X 10.58.0-release.0

**Comment by Morafoka69** [comment]
Go to Piko Settings/Feature Flags/Search and add this:

_recruiting_android_job_tab_

Then switch off the feature. It should look like this:

![Screenshot_20240923-195141_1](https://github.com/user-attachments/assets/a0770e26-9f2e-47aa-951c-e59892ac3cad)

Then restart your app and voila!

**Comment by crimera** [comment]
https://github.com/crimera/piko/commit/14ce811a7b4d885fa6779524aad0b41034a2d8d0
