### ISSUE TITLE
bug: Consistent crash after launching twitter on v10.49.0

### ISSUE THREAD

**Issue by Jman-Github** [crimera/piko#400]
When ever I launch Twitter v10.49.0 patched with all Piko Patches, the app crashes after about 2 - 3 seconds. I attached a logcat log below.
[twitter-logs.txt](https://github.com/user-attachments/files/17059402/twitter-logs.txt)

**Comment by theo546** [comment]
I think you mean 10.59

**Comment by Jman-Github** [comment]
Yeah typo on my end. Closing the issue since it was fixed in latest release.
