### ISSUE TITLE
A promoted post appears in the reply list

### ISSUE THREAD

**Issue by stu2005** [crimera/piko#425]
As stated in the title, the promotional post appeared in the reply list.
![無題1_20241008153803.png](https://github.com/user-attachments/assets/6137cecf-1180-4b55-a133-af6cdbd7481b)

I am using [this](https://github.com/crimera/twitter-apk/releases/tag/10.61.1-release.0) .

**Comment by crimera** [comment]
79d6e35144ffc6c81d3bb36499fc2c22e5a089ac Could you check with the latest dev build? Pushed an update that hopefully removes these ads.

**Comment by stu2005** [comment]
I confirmed that it was hidden. Thank you for fixing it.
