### ISSUE TITLE
10.62.0 and 10.62.1 cant be patched

### ISSUE THREAD

**Issue by isillo** [crimera/piko#428]
Guys? Its been already two days since 10.62.0 released and it cannot be patched, gives failure. 10.62.1 also. Usually crimera response was incredibly fast, we were having updated patches in manner of hours and now its been already two days and no new patches that could work with 10.62.x? Something bad happened? Im worried.

EDIT: typos

**Comment by 5uck3rpunch** [comment]
I'm having the same issue on a Samsung Galaxy Z Fold 6 on one UI 6.1.1 (Android 14).  I first contacted the ReVanced Manager dev, but we discovered this is only an issue when using Crimera/Piko.

I downloaded the X (previously Twitter) 10.62.1-release.0 .apkm from apkmirror.com. I then merge the split .apkm with AntiSplit M. I open ReVanced Manager & choose the antisplit .apk from local storage & use the default patches from the alternative source Crimera to get the Piko patch features. The pacthing runs & pauses for about 9 full seconds on Compiled classes4.dex & then also Compiled classes8.dex. The patching completes fast after that kicking up the full error.
I have cleared all temp & log files. I have also cleared all storage in the Android Settings for this app. I have also uninstalled & reinstalled ReVanced Manager. ReVanced Manager has full permissions in Android Settings for the app.

[revanced-manager_logcat_20241011063022079856.log](https://github.com/user-attachments/files/17342547/revanced-manager_logcat_20241011063022079856.log)

![Screenshot_20241011_064627_ReVanced Manager](https://github.com/user-attachments/assets/ef2a61f5-d462-4738-8ce6-bd8e060aa0cc)

**Comment by andreqsilva78** [comment]
I know the issue here is applying the crimera / piko patches via Revanced Manager. Anyway, while updated patches are not released, one option is to download the apk with the crimera/piko features from the link:

https://github.com/crimera/twitter-apk/releases/tag/10.62.1-release.0

**Comment by crimera** [comment]
Seems to be a manager issue, twitter patches successfully when using the revanced cli tool. The google photos patch also seems to be having the same issues. https://github.com/ReVanced/revanced-manager/issues/2142#issuecomment-2293169291.

**Comment by 5uck3rpunch** [comment]
> Can we reopen until its sorted?

Or at least you work with the ReVanced Manager team to let them know it's not a piko issue. They pushed me here saying it was your issue

**Comment by crimera** [comment]
I think i found the issue, it happens when modifying the strings. 

Seems that the default value of conference_default_title which is  `&#120143; Conference` gets modified into: ![Image](https://github.com/user-attachments/assets/af9e2af9-6371-495c-a0d9-80282fff76a1). Will work on a fix.

**Comment by crimera** [comment]
https://github.com/crimera/piko-patches-test/raw/refs/heads/main/bundle.json

you can test the fix in revanced-manager compose, through this bundle

**Comment by crimera** [comment]
No eta. But you can test the fix in revanced-manager compose, through this bundle
https://github.com/crimera/piko-patches-test/raw/refs/heads/main/bundle.json.

**Comment by crimera** [comment]
Fixed with: c20e16f80499df75176e9080f156e529f4f7d326, 1763137126b9a95df51fe23ce816853ccf0a8f44
