### ISSUE TITLE
Ads have started to show up on latest version of X/Twitter

### ISSUE THREAD

**Issue by Pratik-193** [crimera/piko#432]
Hi,
Ads have started to show up on the last few versions of x/twitter. Ads are shown in comments section and few in timelines section.

Patch version - 1.31.2
x version - 10.62.1
Integrations - v1.31.0

**Comment by crimera** [comment]
79d6e35144ffc6c81d3bb36499fc2c22e5a089ac Could you check with the latest dev build? Pushed an update that hopefully removes these ads.
