### ISSUE TITLE
Big banner on the search page's "For You" tab is showing up again

### ISSUE THREAD

**Issue by bqv** [crimera/piko#435]
Despite being off

**Comment by bqv** [comment]
![Screenshot_2024-10-26-00-53-08-33_0b2fce7a16bf2b728d6ffa28c8d60efb.jpg](https://github.com/user-attachments/assets/6a0598da-5e1b-4b47-8a58-94cba64b4510)

What will it take to kill these ads, @crimera

**Comment by crimera** [comment]
6bb196bb01d7f09f6442d635e556fc985b1b9751
