### ISSUE TITLE
Question/request

### ISSUE THREAD

**Issue by Hutchyy9** [crimera/piko#436]
Hi,

Is it possible to stop the bottom navigation bar from disappearing when scrolling?
And is it possible to get rid of "premium" and "Grok"?

Thanks

**Comment by crimera** [comment]
> get rid of "premium" and "Grok"?

subscriptions_enabled - disabled

> stop the bottom navigation bar from disappearing when scrolling?

android_main_immersive_bottom_tabs_hide_on_scroll - disabled

**Comment by Hutchyy9** [comment]
Thanks. Is this possible on ReVanced too as I can't see the options there?

**Comment by crimera** [comment]
If you mean by adding them into the revanced manager directly then no, add them in the feature flags screen in piko settings after patching the apk.

**Comment by Hutchyy9** [comment]
Great, thanks! Is there any other feature flags you'd recommend adding?
