### ISSUE TITLE
How to use Piko patches via ReVanced Manager now (after changing the alternative sources settings window)?

### ISSUE THREAD

**Issue by DmB-Ekb** [crimera/piko#469]
In the last version of ReVanced Manager, the integration settings have disappeared from the alternative sources settings window:
![image](https://github.com/user-attachments/assets/21b6a1a6-b8d0-429d-a9ed-7351b76d7384)
As a result, when trying to patch a Twitter .apk, ReVanced Manager does not see any available patches for it:
![image](https://github.com/user-attachments/assets/774d3e9e-5679-4a45-b79a-87f9887378b6)
![image](https://github.com/user-attachments/assets/6ef605d9-3019-498e-821a-6463daa948e1)
This may be ReVanced Manager bug that will be fixed soon. But how can we use Piko patches through ReVanced Manager now if it won't?

**Comment by crimera** [comment]
You can't, the current patches are not compatible with the new revanced manager versions. https://github.com/inotia00/revanced-manager you may use inotia00's for now.

**Comment by DmB-Ekb** [comment]
Thank you, I understand.
It seems that for people who are not very familiar with the diversity of projects and their compatibility with each other, it will be easier to take ready-made patched Twitter files in your repository, thank you very much for it )

**Comment by shifoc** [comment]
> You can't, the current patches are not compatible with the new revanced manager versions. https://github.com/inotia00/revanced-manager you may use inotia00's for now.

https://github.com/inotia00/ReVanced_Extended/issues/2514

It's giving an error @crimera
