### ISSUE TITLE
No patches found for the selected app

### ISSUE THREAD

**Issue by barribad** [crimera/piko#484]
I set alternative resources. I deleted cache. I even reset the manager, but there are still not any patches shown after I select Twitter 10.68.1* or 10.68.2* APKs. Is there a way to fix? Thanks in advance

![Screenshot_20241130_232524_ReVanced Manager](https://github.com/user-attachments/assets/020a4e88-1c57-48d1-9255-bf355b235f14)

Edit: It's for all APKs, not just those two*

**Comment by doubior** [comment]
solution in https://github.com/crimera/piko/issues/469#issue-2654348019
sorry, I should have done better research before opening

**Comment by doubior** [comment]
Edit again (sorry)
I tried to use RVX Manager, but after trying to patch the APK, it stucks then

![Screenshot_20241130_233628_RVX Manager](https://github.com/user-attachments/assets/1db62fc9-e01c-4495-82cb-326c9e1c82f6)

**Comment by barribad** [comment]
Solution (final). https://github.com/crimera/twitter-apk exists. Sorry again🙏
