### ISSUE TITLE
Custom navigation bug?

### ISSUE THREAD

**Issue by Quasar-0330** [crimera/piko#489]
Tapping `Premium > Custom Navigation` will open the URL https://www.x.com/settings/custom_navigation in the browser. The browser is opened with the App Icon as well.

**Comment by Quasar-0330** [comment]
I've tried several previous patches, Twitter versions, with the same results.

**Comment by Bec-de-Xorbin** [comment]
Do this but for X instead: https://www.reddit.com/r/revancedapp/comments/13ewsex/guide_on_how_to_set_revanced_as_default_system/

**Comment by Quasar-0330** [comment]
It's fixed perfectly. Thank you!
