### ISSUE TITLE
Mod settings crash when rooted

### ISSUE THREAD

**Issue by jojobozo** [crimera/piko#51]
When I tap on Mod settings the app is crashing, using Revancify rooted

**Comment by Rekik88** [comment]
It happend with me too when using revancify or revanced manager with root. Installing the patched apk without root fixed it for me.

**Comment by LovecraftianGodsKiller** [comment]
This is still happening for me and I'm not rooted.  
Gonna try patching it via the cli and see if that does anything.

**Comment by LovecraftianGodsKiller** [comment]
> This is still happening for me and I'm not rooted. Gonna try patching it via the cli and see if that does anything.

Update, it worked.

**Comment by crimera** [comment]
https://github.com/crimera/piko/commit/81616443f2104eb1633c2c92c555f45341a7680e
